name: Restore Node.js env
description: Node.js によるタスクランナー基盤を復元する

runs:
  using: composite
  steps:
    - name: Set node version
      shell: bash
      run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Set pnpm version
        shell: bash
        run: |
          pnpm=$(cat package.json | jq -r .engines.pnpm)
          echo "PNPM_VERSION=${pnpm}" >> $GITHUB_ENV

    - name: Echo
        shell: bash
        run: echo "PNPM_VERSION is \"$PNPM_VERSION\"."

    - uses: pnpm/action-setup@v2.2.2
      with:
        version: ${{ env.PNPM_VERSION }}

    - name: Restore node_modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
